# Generated by Django 2.2.28 on 2026-02-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20260206_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='exit'),
            preserve_default=False,
        ),
    ]
